services:
  app:
    container_name: market-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - my-network
  db:
    image: postgres:17-alpine
    container_name: market-psql
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: market_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U market_user -d market_db"]
      interval: 5s
      start_period: 15s
      timeout: 10s
      retries: 20
    
networks:
  my-network:
    name: my-network